const nameArray = [
    "Barack Obama",
    "Steph Curry",
    "Your next door neighbor",
    "Nate",
    "Elon Musk",
    "Keanu Reeves",
    "Salt Bae",
    "Darude",
    "Chuck Norris",
    "Rick Astley",
    "Doge",
    "Grumpy Cat",
    "Donald Trump",
    "Rick Astley",
    "Shrek",
    "Jesus",
    "Dank Memer",
    "Mr Mosby",
    "Wendy",
    "Barry McKocner",
    "Jordan Peele",
    "Harry Balzac",
    "Kevin Hart",
    "Eda Jerk",
    "Kim Jong Un",
    "Drake",
    "Kamala Harris",
    "Chris Peanuts",
    "A honey badger",
    "Discord Dog",
    "Rihanna",
    "Mr. Clean",
    "Satan",
    "ayylien",
    "Selena Gomez",
    "Harry",
    "Elizabeth Warren",
    "Dawn Keebals",
    "Billie Eyelash",
    "Joe Montana",
    "Mr. Ja-cough",
    "Your step-sister",
    "Chuck Norris",
    "Your drunk self",
    "Dr. Phil",
    "Default Jonesy",
    "Cardi B",
    "Sans",
    "Peter Dinklage",
    "Nicki Minaj",
    "Dwight Shrute",
    "Timmy",
    "Donald Glover",
    "That fart you've been holding in",
    "Paula Deen",
    "Lady Gaga",
    "Oprah",
    "Elon Musk",
    "Taylor Swift",
    "Melmsie's Beard",
    "Justin Bieber",
    "Toby Turner",
    "That girl whose bed you woke up in last night and you're too afraid to ask her name because you might come off as rude",
    "AirPod Jerk",
    "Your mom",
    "Mike Hoochie",
    "Mike Ock",
    "Spoopy Skelo",
    "Chungus",
    "Flo from Progressive",
    "That tiktok star that shows a little too much butt",
    "Sir Cole Jerkin",
    "T series",
    "Jennifer Lopez",
    "Barack Obama",
    "Cersei Lannister",
    "Carole Baskin",
    "Gordon Ramsay",
    "Thanos",
    "Emilia Clarke",
    "Bart Simpson",
    "Bongo cat",
    "Keanu Reeves",
    "Mr. Beast",
    "Annoying Ass Clown",
    "That lion from the kids movie that vaguely resembles the story of Jesus Christ",
    "That imposter who was too scared to murder you just because he didn't want to look sus",
    "TikTok Bitch",
    "Evil Nun",
    "Evil Kid",
    "Granny",
    "Grandpa",
    "Alotta Fagina",
    "Joe",
    "Jinn",
    "Mare",
    "Wraith",
    "Mike",
    "SSSniperWolf",
    "SSundee",
    "JoniOliveros",
    "MargeJerman",
    "SteveMarrow",
    "SierraSultan",
    "PaigeTelecanos",
    "Messi",
    "Rory Harris",
    "Raibaru Fumetsu",
    "Megami Saikou",
    "Umeji Kizugichi",
    "Kokichi Ouma",
    "Jessica Carter",
    "Osoro Shidesu",
    "Hokuto Furukizu",
    "Daisoku Surukizu",
    "Hayanari Tsumeato",
    "Kuroko Kamenaga",
    "Kyoshi Tachibana",
    "Gaku Hikitsuri",
    "Akane Toriyasu",
    "Shiromi Torayoshi",
    "Oka Ruto",
    "Osana Najimi",
    "Sigils",
    "Biffle",
    "Henwy",
    "Ambrew",
    "nicovald",
    "Doctor Slone",
    "Brutus",
    "Jules",
    "GarryBlox",
    "Libby McFostor",
    "Bertrand Pickwick",
    "Bertrand Hood",
    "@BitlifeApp",
    "Senpai",
];

const giveCoinResponse = [
    "Oh! You poor thing... Take",
    "I'm feeling generous today... Take",
    "Just don't spend it on drugs. Here's",
]
const noCoinResponse = [
    "Go get a job!",
    "Go Away",
    "Maybe if you didn't stream all day, you'd have money.",
    "I'm too poor",
    "I forgot my wallet",
]

module.exports = { 
    nameArray, 
    giveCoinResponse, 
    noCoinResponse 
};